package com.top.cap.model;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;

import org.springframework.stereotype.Component;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonProperty;

@Component
@DynamoDBTable(tableName="Books")
public class Book {
	
	private static final String BOOK_CATEGORY = "Book";
	
	@Size(min = 1, max = 40)
	@JsonProperty("id")
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName="Id")
	private String id;
	
	@NotBlank(message = "Title is mandatory")
	@Size(min = 1, max = 40)
	@JsonProperty("title")
	@DynamoDBAttribute(attributeName="Title")
	private String title;
	
	@Size(min = 1, max = 40)
	@JsonProperty("stock")
	@DynamoDBAttribute(attributeName="Stock")
	private String stock;
	
	@Size(min = 1, max = 40)
	@JsonProperty("isbn")
	@DynamoDBAttribute(attributeName="ISBN")
	private String ISBN;
	
	@JsonProperty("price")
	@DynamoDBAttribute(attributeName="Price")
	private int price;

	@Size(min = 1, max = 40)
	@DynamoDBAttribute(attributeName="ProductCategory")
	private String productCategory = BOOK_CATEGORY;
	
	@JsonProperty("inPublication")
	@DynamoDBAttribute(attributeName="InPublication")
	private boolean inPublication;
	
	public String getId() {
		return id;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((stock == null) ? 0 : stock.hashCode());
		result = prime * result + ((title == null) ? 0 : title.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Book other = (Book) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (stock == null) {
			if (other.stock != null)
				return false;
		} else if (!stock.equals(other.stock))
			return false;
		if (title == null) {
			if (other.title != null)
				return false;
		} else if (!title.equals(other.title))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Book [id=" + id + ", title=" + title + ", stock=" + stock + "]";
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getStock() {
		return stock;
	}

	public void setStock(String stock) {
		this.stock = stock;
	}
}
